export interface DepartmentItem {
    id: number;
    code: string;
    name: string;
    type: "root" | "province-dept" | "ministry" | "supervision" | "temple" | "judicial" | "center" | "department" | "group";
    level: number;
    parentId: number | null;
    parentName: string | null;
    leader: string;
    status: "enabled" | "disabled";
    sort: number;
    remark: string;
}

export const tangDepartmentList: DepartmentItem[] = [
    {
        id: 1,
        code: "tang-center",
        name: "大唐中央",
        type: "root",
        level: 0,
        parentId: null,
        parentName: null,
        leader: "皇帝",
        status: "enabled",
        sort: 1,
        remark: "中央最高统治中枢",
    },
    {
        id: 2,
        code: "zhongshusheng",
        name: "中书省",
        type: "province-dept",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "中书令",
        status: "enabled",
        sort: 1,
        remark: "负责起草诏令",
    },
    {
        id: 3,
        code: "menxiasheng",
        name: "门下省",
        type: "province-dept",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "侍中",
        status: "enabled",
        sort: 2,
        remark: "负责审议封驳",
    },
    {
        id: 4,
        code: "shangshusheng",
        name: "尚书省",
        type: "province-dept",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "尚书令",
        status: "enabled",
        sort: 3,
        remark: "负责行政执行，统辖六部",
    },
    {
        id: 5,
        code: "yushitai",
        name: "御史台",
        type: "supervision",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "御史大夫",
        status: "enabled",
        sort: 4,
        remark: "负责监察百官",
    },
    {
        id: 6,
        code: "dalisi",
        name: "大理寺",
        type: "judicial",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "大理寺卿",
        status: "enabled",
        sort: 5,
        remark: "负责审判事务",
    },
    {
        id: 7,
        code: "taichangsi",
        name: "太常寺",
        type: "temple",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "太常卿",
        status: "enabled",
        sort: 6,
        remark: "负责礼乐祭祀",
    },
    {
        id: 8,
        code: "guanglusi",
        name: "光禄寺",
        type: "temple",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "光禄卿",
        status: "enabled",
        sort: 7,
        remark: "负责膳食宴享",
    },
    {
        id: 9,
        code: "weiweisi",
        name: "卫尉寺",
        type: "temple",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "卫尉卿",
        status: "enabled",
        sort: 8,
        remark: "负责宫门屯卫仪仗",
    },
    {
        id: 10,
        code: "zongzhengsi",
        name: "宗正寺",
        type: "temple",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "宗正卿",
        status: "enabled",
        sort: 9,
        remark: "负责宗室事务",
    },
    {
        id: 11,
        code: "taipusi",
        name: "太仆寺",
        type: "temple",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "太仆卿",
        status: "enabled",
        sort: 10,
        remark: "负责车马舆驾",
    },
    {
        id: 12,
        code: "honglusi",
        name: "鸿胪寺",
        type: "temple",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "鸿胪卿",
        status: "enabled",
        sort: 11,
        remark: "负责宾礼与外交接待",
    },
    {
        id: 13,
        code: "sinongsi",
        name: "司农寺",
        type: "temple",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "司农卿",
        status: "enabled",
        sort: 12,
        remark: "负责仓储农业财政相关事务",
    },
    {
        id: 14,
        code: "taifusi",
        name: "太府寺",
        type: "temple",
        level: 1,
        parentId: 1,
        parentName: "大唐中央",
        leader: "太府卿",
        status: "enabled",
        sort: 13,
        remark: "负责财货管理",
    },
    {
        id: 15,
        code: "libu-official",
        name: "吏部",
        type: "ministry",
        level: 2,
        parentId: 4,
        parentName: "尚书省",
        leader: "吏部尚书",
        status: "enabled",
        sort: 1,
        remark: "负责官员任免考核",
    },
    {
        id: 16,
        code: "hubu",
        name: "户部",
        type: "ministry",
        level: 2,
        parentId: 4,
        parentName: "尚书省",
        leader: "户部尚书",
        status: "enabled",
        sort: 2,
        remark: "负责户籍财政赋税",
    },
    {
        id: 17,
        code: "libu-ritual",
        name: "礼部",
        type: "ministry",
        level: 2,
        parentId: 4,
        parentName: "尚书省",
        leader: "礼部尚书",
        status: "enabled",
        sort: 3,
        remark: "负责礼仪科举外交",
    },
    {
        id: 18,
        code: "bingbu",
        name: "兵部",
        type: "ministry",
        level: 2,
        parentId: 4,
        parentName: "尚书省",
        leader: "兵部尚书",
        status: "enabled",
        sort: 4,
        remark: "负责军事行政",
    },
    {
        id: 19,
        code: "xingbu",
        name: "刑部",
        type: "ministry",
        level: 2,
        parentId: 4,
        parentName: "尚书省",
        leader: "刑部尚书",
        status: "enabled",
        sort: 5,
        remark: "负责司法刑狱",
    },
    {
        id: 20,
        code: "gongbu",
        name: "工部",
        type: "ministry",
        level: 2,
        parentId: 4,
        parentName: "尚书省",
        leader: "工部尚书",
        status: "enabled",
        sort: 6,
        remark: "负责工程营造水利",
    },
];


export const enterpriseDepartmentList: DepartmentItem[] = [
    {
        id: 101,
        code: "company-root",
        name: "集团总部",
        type: "root",
        level: 0,
        parentId: null,
        parentName: null,
        leader: "CEO",
        status: "enabled",
        sort: 1,
        remark: "企业最高管理机构",
    },
    {
        id: 102,
        code: "strategy-center",
        name: "战略管理中心",
        type: "center",
        level: 1,
        parentId: 101,
        parentName: "集团总部",
        leader: "战略副总裁",
        status: "enabled",
        sort: 1,
        remark: "负责战略规划与经营分析",
    },
    {
        id: 103,
        code: "hr-center",
        name: "人力资源中心",
        type: "center",
        level: 1,
        parentId: 101,
        parentName: "集团总部",
        leader: "HRD",
        status: "enabled",
        sort: 2,
        remark: "负责招聘、绩效、组织发展",
    },
    {
        id: 104,
        code: "finance-center",
        name: "财务中心",
        type: "center",
        level: 1,
        parentId: 101,
        parentName: "集团总部",
        leader: "CFO",
        status: "enabled",
        sort: 3,
        remark: "负责财务核算与预算管理",
    },
    {
        id: 105,
        code: "legal-center",
        name: "法务与合规中心",
        type: "center",
        level: 1,
        parentId: 101,
        parentName: "集团总部",
        leader: "法务总监",
        status: "enabled",
        sort: 4,
        remark: "负责法务、审计、合规",
    },
    {
        id: 106,
        code: "tech-center",
        name: "技术中心",
        type: "center",
        level: 1,
        parentId: 101,
        parentName: "集团总部",
        leader: "CTO",
        status: "enabled",
        sort: 5,
        remark: "负责研发与技术平台建设",
    },
    {
        id: 107,
        code: "product-center",
        name: "产品中心",
        type: "center",
        level: 1,
        parentId: 101,
        parentName: "集团总部",
        leader: "产品副总裁",
        status: "enabled",
        sort: 6,
        remark: "负责产品规划与设计",
    },
    {
        id: 108,
        code: "marketing-center",
        name: "市场中心",
        type: "center",
        level: 1,
        parentId: 101,
        parentName: "集团总部",
        leader: "市场副总裁",
        status: "enabled",
        sort: 7,
        remark: "负责品牌、投放、增长",
    },
    {
        id: 109,
        code: "sales-center",
        name: "销售中心",
        type: "center",
        level: 1,
        parentId: 101,
        parentName: "集团总部",
        leader: "销售副总裁",
        status: "enabled",
        sort: 8,
        remark: "负责客户销售与渠道拓展",
    },
    {
        id: 110,
        code: "customer-success-center",
        name: "客户成功中心",
        type: "center",
        level: 1,
        parentId: 101,
        parentName: "集团总部",
        leader: "客户成功总监",
        status: "enabled",
        sort: 9,
        remark: "负责交付、续费、客户运营",
    },
    {
        id: 111,
        code: "backend-rd",
        name: "后端研发部",
        type: "department",
        level: 2,
        parentId: 106,
        parentName: "技术中心",
        leader: "后端研发经理",
        status: "enabled",
        sort: 1,
        remark: "负责服务端系统研发",
    },
    {
        id: 112,
        code: "frontend-rd",
        name: "前端研发部",
        type: "department",
        level: 2,
        parentId: 106,
        parentName: "技术中心",
        leader: "前端研发经理",
        status: "enabled",
        sort: 2,
        remark: "负责 Web 与中后台前端研发",
    },
    {
        id: 113,
        code: "mobile-rd",
        name: "移动端研发部",
        type: "department",
        level: 2,
        parentId: 106,
        parentName: "技术中心",
        leader: "移动端研发经理",
        status: "enabled",
        sort: 3,
        remark: "负责 iOS/Android/跨端研发",
    },
    {
        id: 114,
        code: "qa",
        name: "测试质量部",
        type: "department",
        level: 2,
        parentId: 106,
        parentName: "技术中心",
        leader: "测试经理",
        status: "enabled",
        sort: 4,
        remark: "负责测试与质量保障",
    },
    {
        id: 115,
        code: "devops",
        name: "基础设施与运维部",
        type: "department",
        level: 2,
        parentId: 106,
        parentName: "技术中心",
        leader: "运维经理",
        status: "enabled",
        sort: 5,
        remark: "负责 CI/CD、云资源、监控",
    },
    {
        id: 116,
        code: "product-b",
        name: "B端产品部",
        type: "department",
        level: 2,
        parentId: 107,
        parentName: "产品中心",
        leader: "B端产品经理",
        status: "enabled",
        sort: 1,
        remark: "负责后台与企业产品规划",
    },
    {
        id: 117,
        code: "product-c",
        name: "C端产品部",
        type: "department",
        level: 2,
        parentId: 107,
        parentName: "产品中心",
        leader: "C端产品经理",
        status: "enabled",
        sort: 2,
        remark: "负责用户端产品规划",
    },
    {
        id: 118,
        code: "design",
        name: "设计体验部",
        type: "department",
        level: 2,
        parentId: 107,
        parentName: "产品中心",
        leader: "设计总监",
        status: "enabled",
        sort: 3,
        remark: "负责视觉与交互设计",
    },
    {
        id: 119,
        code: "brand",
        name: "品牌部",
        type: "department",
        level: 2,
        parentId: 108,
        parentName: "市场中心",
        leader: "品牌经理",
        status: "enabled",
        sort: 1,
        remark: "负责品牌传播与公关",
    },
    {
        id: 120,
        code: "growth",
        name: "增长运营部",
        type: "department",
        level: 2,
        parentId: 108,
        parentName: "市场中心",
        leader: "增长经理",
        status: "enabled",
        sort: 2,
        remark: "负责投放、转化、用户增长",
    },
];